### ISSUE TITLE
ffmpeg file dump fails

### ISSUE THREAD

**Issue by beingmountain23** [ethand91/mediasoup3-record-demo#11]
When the stderr and stdout hooks of a process are commented out, the ffmpeg process seems to be failing.
Have you ever come across this?

It creates a small file of 600 bytes without any content.

**Comment by ethand91** [comment]
If you comment out the stderr and stdout hooks the ffmpeg process has nothing to output to,
when that happens the buffer gets full and the process ends.
You need to let the ffmpeg process output to somewhere.

**Comment by beingmountain23** [comment]
Thank you so much for your input. I understand now.
