### ISSUE TITLE
Recorded file have size of 0 Byte

### ISSUE THREAD

**Issue by itzmanish** [ethand91/mediasoup3-record-demo#14]
Files are created on clicking record but after stop recording files are still 0 byte of size.

**Comment by itzmanish** [comment]
This occurs with gstreamer.

**Comment by ethand91** [comment]
Can you check the stats of the RTP consumer and check that it is receiving packets?

**Comment by itzmanish** [comment]
This is what I get in server log.

socket::message [jsonMessage:{
  action: 'start-record',
  sessionId: '9b8d0330-ab98-11ea-a490-e366f9d40a88'
}]
handleStartRecordRequest() [data:{
  action: 'start-record',
  sessionId: '9b8d0330-ab98-11ea-a490-e366f9d40a88'
}]
publishProducerRtpStream()
createTransport() [type:plain. options:{ listenIp: '127.0.0.1', rtcpMux: false, comedia: false }]
publishProducerRtpStream()
createTransport() [type:plain. options:{ listenIp: '127.0.0.1', rtcpMux: false, comedia: false }]
gstreamer::process::stdout::data [data:'Setting pipeline to PAUSED ...\n']
gstreamer::process::stdout::data [data:'Pipeline is live and does not need PREROLL ...\n']
gstreamer::process::stdout::data [data:'/GstPipeline:pipeline0/GstUDPSrc:udpsrc0.GstPad:src: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, payload=(int)101, encoding-name=(string)VP8, ssrc=(uint)1974725326\n' +      '/GstPipeline:pipeline0/GstRtpBin:rtpbin.GstGhostPad:recv_rtp_sink_0.GstProxyPad:proxypad0: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, payload=(int)101, encoding-name=(string)VP8, ssrc=(uint)1974725326\n' +     '/GstPipeline:pipeline0/GstRtpBin:rtpbin/GstFunnel:funnel0.GstFunnelPad:funnelpad0: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, payload=(int)101, encoding-name=(string)VP8, ssrc=(uint)1974725326\n']
gstreamer::process::stdout::data [data:'/GstPipeline:pipeline0/GstRtpBin:rtpbin.GstGhostPad:recv_rtp_sink_0: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, payload=(int)101, encoding-name=(string)VP8, ssrc=(uint)1974725326\n' +
  '/GstPipeline:pipeline0/GstUDPSrc:udpsrc1.GstPad:src: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, payload=(int)100, encoding-name=(string)OPUS, ssrc=(uint)2922796142\n' +
  '/GstPipeline:pipeline0/GstRtpBin:rtpbin.GstGhostPad:recv_rtp_sink_1.GstProxyPad:proxypad1: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, payload=(int)100, encoding-name=(string)OPUS, ssrc=(uint)2922796142\n' +    '/GstPipeline:pipeline0/GstRtpBin:rtpbin/GstFunnel:funnel2.GstFunnelPad:funnelpad1: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, payload=(int)100, encoding-name=(string)OPUS, ssrc=(uint)2922796142\n' +
  '/GstPipeline:pipeline0/GstRtpBin:rtpbin.GstGhostPad:recv_rtp_sink_1: caps = application/x-rtp, media=(string)audio, clock-rate=(int)48000, payload=(int)100, encoding-name=(string)OPUS, ssrc=(uint)2922796142\n']
gstreamer::process::stdout::data [data:'Setting pipeline to PLAYING ...\n']
gstreamer::process::stdout::data [data:'New clock: GstSystemClock\n']
socket::message [jsonMessage:{
  action: 'stop-record',
  sessionId: '9b8d0330-ab98-11ea-a490-e366f9d40a88'
}]
handleStopRecordRequest() [data:{
  action: 'stop-record',
  sessionId: '9b8d0330-ab98-11ea-a490-e366f9d40a88'
}]
kill() [pid:71408]

**Comment by ethand91** [comment]
Can you check the stats of the RTP consumer and confirm packets are being received?

**Comment by dorinmusteata** [comment]
Hi , i have the same problem with file size being 0 bytes , i think the problem is somewhere in command parameters my packets are being received 100%.

Haven't tested with ffmpeg , this problem occurs when using gstreamer , with video source type.
Audio source work perfectly.

OS: macOS Catalina

P.S @ethand91 can you confirm that video recording with gstreamers works on your machine ?

**Comment by ethand91** [comment]
This was tested using Mac OS Catalina, can you check you have the vpx decoders/encoders?

```
gst-inspect-1.0  | grep vpx
```

Also could you share the rtpParameters of the relaying consumer?

**Comment by dorinmusteata** [comment]
```vpx:  vp9enc: On2 VP9 Encoder
vpx:  vp9dec: On2 VP9 Decoder
vpx:  vp8enc: On2 VP8 Encoder
vpx:  vp8dec: On2 VP8 Decoder

----

{
  codecs: [
    {
      mimeType: 'video/VP8',
      payloadType: 101,
      clockRate: 90000,
      parameters: {},
      rtcpFeedback: [Array]
    },
    {
      mimeType: 'video/rtx',
      payloadType: 102,
      clockRate: 90000,
      parameters: [Object],
      rtcpFeedback: []
    }
  ],
  headerExtensions: [
    {
      uri: 'urn:ietf:params:rtp-hdrext:sdes:mid',
      id: 1,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time',
      id: 4,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01',
      id: 5,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07',
      id: 6,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'urn:ietf:params:rtp-hdrext:framemarking',
      id: 7,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'urn:3gpp:video-orientation',
      id: 11,
      encrypt: false,
      parameters: {}
    },
    {
      uri: 'urn:ietf:params:rtp-hdrext:toffset',
      id: 12,
      encrypt: false,
      parameters: {}
    }
  ],
  encodings: [ { ssrc: 915808166, rtx: [Object], scalabilityMode: 'S3T3' } ],
  rtcp: { cname: 'B4G+p/IEq2WrHllq', reducedSize: true, mux: true },
  mid: '0'
}
```

**Comment by ethand91** [comment]
Could you try updating the source and see if that works?

**Comment by dorinmusteata** [comment]
Works for me. Thanks.

**Comment by ethand91** [comment]
Great! Seems to be the payloadTypes in the SDP wasn't correct.
@itzmanish Does it work for you?

**Comment by urispmts** [comment]
I use ffmpeg, but I had the same issue today.
For me, the problem was the listenIp in server config. I set it to 0.0.0.0 first and had the error.
When I set it to 127.0.0.1 the error was resolved.
Found it in this issue: #7

**Comment by itzmanish** [comment]
> Great! Seems to be the payloadTypes in the SDP wasn't correct.
> @itzmanish Does it work for you?

nope. I am running it on 0.0.0.0 and got error while running with gstreamer.

```
publishProducerRtpStream()
createTransport() [type:plain. options:{ listenIp: '0.0.0.0', rtcpMux: true, comedia: false }]
publishProducerRtpStream()
createTransport() [type:plain. options:{ listenIp: '0.0.0.0', rtcpMux: true, comedia: false }]
createProcess() [sdpString:v=0
  o=- 0 0 IN IP4 127.0.0.1
  s=FFmpeg
  c=IN IP4 127.0.0.1
  t=0 0
  m=video 25313 RTP/AVP 101 
  a=rtpmap:101 VP8/90000
  a=sendonly
  m=audio 29868 RTP/AVP 100 
  a=rtpmap:100 opus/48000/2
  a=sendonly
  ]
commandArgs:[
  '-loglevel',
  'debug',
  '-protocol_whitelist',
  'pipe,udp,rtp',
  '-fflags',
  '+genpts',
  '-f',
  'sdp',
  '-i',
  'pipe:0',
  '-map',
  '0:v:0',
  '-c:v',
  'copy',
  '-map',
  '0:a:0',
  '-strict',
  '-2',
  '-c:a',
  'copy',
  '-flags',
  '+global_header',
  './files/1592531311746.webm',
  [length]: 23
]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Readable.ondata (_stream_readable.js:717:22)
    at Readable.emit (events.js:315:20)
    at Readable.read (_stream_readable.js:506:10)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Socket.onerror (_stream_readable.js:753:7)
    at Socket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:679:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:154:17) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by itzmanish** [comment]
Also I don'tunderstand why in SDP there is FFMPEG?

**Comment by ethand91** [comment]
You need to set webRtcTransport.ip to 127.0.0.1 or your local network, it will not work with 0.0.0.0.

**Comment by itzmanish** [comment]
> You need to set webRtcTransport.ip to 127.0.0.1 or your local network, it will not work with 0.0.0.0.

Still not working with 127.0.0.1

**Comment by ethand91** [comment]
if the page and the server are not on the same machine 127.0.0.1 will not work, try using your network ip.

**Comment by jithinkradhakrishnan** [comment]
connecting server remotely 
using network ip

still the recording file has zero mb only
