### ISSUE TITLE
Recording 2 samples at once ?

### ISSUE THREAD

**Issue by dorinmusteata** [ethand91/mediasoup3-record-demo#16]
Is it possibile to record 2 samples of 1 video ? 

I tried running the process twice with gstreamer but the second video does work , i'm not very familiar with gstreamer though and i'm getting this error:

info: [GStreamer - err.data]: data: 0:00:01.029949000 35142 0x7f901c02d240 FIXME               basesink gstbasesink.c:3248:gboolean gst_base_sink_default_event(GstBaseSink *, GstEvent *):<filesink0> stream-start event without group-id. Consider implementing group-id handling in the upstream elements

**Comment by ethand91** [comment]
You would need to create an extra video rtpConsumer and relay that to a different gstreamer process.
