### ISSUE TITLE
error: Could not open file "./files/1594237790634.webm" for writing.\n

### ISSUE THREAD

**Issue by sraza295** [ethand91/mediasoup3-record-demo#17]
When I run this project.
I got this error "error: Could not open file "./files/1594237790634.webm" for writing.\n".
After that I created a folder named as 'files"., still this error came.
I am attaching some screenshot.
![server console screenshot](https://user-images.githubusercontent.com/37663062/86964014-0c551300-c183-11ea-8cc8-c09d8df9dd9c.png)

![Project structure](https://user-images.githubusercontent.com/37663062/86964102-2ee72c00-c183-11ea-88fc-a57e03cfa717.png)

**Comment by ethand91** [comment]
The files directory must be created at the root of the directory, not in the src folder. The name is also missing an 's'

**Comment by sraza295** [comment]
@ethand91 
Thank you for reply.
I will implement it what you told.

**Comment by sraza295** [comment]
@ethand91 .
Thanks it is working now.
I have one doubt, Can I record of all stream in one video?
Suppose there are 4 people joined in a room. So how is possible to record the video of all people?
How we can record of all people like zoom application?

**Comment by ethand91** [comment]
You would need to receive all 4 streams in the same GStreamer/FFmpeg pipeline and merge them into 1 file.
