### ISSUE TITLE
isPortOpen from port.js is broken

### ISSUE THREAD

**Issue by sstativa** [ethand91/mediasoup3-record-demo#18]
`isPortOpen()` is broken, ex. socket is `undefined`. 
But apart from this, there is a logic problem. `resolve` would actually mean that port is "busy", and `reject` would mean that the port is free and can be used by the script.

**Comment by ethand91** [comment]
Thanks, I'll fix this when I get time. Also need to check UDP port availability.

**Comment by KiPSOFT** [comment]
Try this;

```
const net = require('net');
const socket = new net.Socket();

```

**Comment by ethand91** [comment]
Decided to remove this function as it's hard to detect if the UDP port is available. Right now it uses TCP.
