### ISSUE TITLE
Record video only stream

### ISSUE THREAD

**Issue by mkhahani** [ethand91/mediasoup3-record-demo#2]
Hi
Trying to record a video stream without audio using ffmpeg with the following sdp:

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=FFmpeg
c=IN IP4 127.0.0.1
t=0 0
m=video ${video.remoteRtpPort} RTP/AVP 101
a=rtpmap:101 VP8/90000
a=sendonly
```
 But it fails: 
> ...
> Applying option map (set input stream mapping) with argument `0:a:0`.
> Stream map `0:a:0` matches no streams.
> To ignore this, add a trailing '?' to the map

**Comment by ethand91** [comment]
Hello,
FFmpeg is expecting an audio stream, which there isn't any.
You will also need to remove the audio args and audio rtcp args from the command args being passed to FFmpeg.

**Comment by mkhahani** [comment]
Thanks for the tip. It's working now. 👍
