### ISSUE TITLE
Video not recording after track replace.

### ISSUE THREAD

**Issue by bphkns** [ethand91/mediasoup3-record-demo#20]
When I update the track in client side with producer.replaceTrack() the recording frame got stuck to the last frame of the original track

**Comment by ethand91** [comment]
Are you using FFmpeg or GStreamer? 
Also can you check the server logs?

**Comment by bphkns** [comment]
I am using GSTREAMER. It is throwing

*error: caps changed are not supported by matroska*

**Comment by ethand91** [comment]
The error is caused by a change of resolution/framerate during the recording (640x480 was changed to 1280x720). The muxer does not allow this so you would need to set the caps on the gstreamer pipeline or encode the video to always be a certain resolution/framework.
