### ISSUE TITLE
Launching the app dev server does not load correct webpage

### ISSUE THREAD

**Issue by zro00** [ethand91/mediasoup3-record-demo#22]
Launching the app via the instructions does not load the index html from the dist directory.

Instructions to repeat:
1. install the dependancies with npm install
2. Run the app with: npm run dev
3. Typing https://localhost:8080 does not load webpage in fact the correct address to use is https://localhost:8080/dist

The instructions does not contain any information about having to navigate to this page.
![issue](https://user-images.githubusercontent.com/64754448/88475555-41d15e80-ceee-11ea-9db5-5b1e02f71a3d.png)

**Comment by ethand91** [comment]
Thanks fixed.
