### ISSUE TITLE
Documentation missing Server ENV option

### ISSUE THREAD

**Issue by zro00** [ethand91/mediasoup3-record-demo#23]
The README is missing an important Server ENV parameter:

SERVER_PORT---->Integer---->The server port number you wish to use. Please note the default is port 3000
Please note if you update this parameter the app must also be updated with the new port 
Please modify the index.js file websocket address with the new port number:
const socket = new WebSocket(`wss://${window.location.hostname}:[NEW PORT NUMBER]`);

**Comment by ethand91** [comment]
Thanks, added.
