### ISSUE TITLE
Demo Request: Switching between multiple video tracks

### ISSUE THREAD

**Issue by eabovsky** [ethand91/mediasoup3-record-demo#28]
I've been looking at your example, and attempting to figure out how to do an "active speaker" recording implementation. Do you have any idea how to negotiate/renegotiate multiple video tracks with FFMPEG or Gstreamer as participants might come and go, then then specify which track to actively record/map?

**Comment by Dirvann** [comment]
I would think you could make ffmpeg keep listening to the specific port to the rtp stream and let ffmpeg wait for reconnection when you switch producer. [How to make ffmpeg wait](https://stackoverflow.com/questions/34718902/ask-to-ffmpeg-to-wait-the-reconnection-of-rtp-source)
This way you can have a single file for the selected users. Then you still have to choose which one is the active one. I haven't tested this specifically myself yet.

If you want to have everyone recorded with people coming in and out of the stream, I suggest recording them all separately and saving their start time to then compile all the files together. 
I'm currently working on a package that is able to combine all the separately recorded videos into one single video looking just like a web conference. I'll be releasing a first version soon.

**Comment by eabovsky** [comment]
Are you sure it's possible to make ffmpeg to keep listening for reconnection? I'll do some exploring there.

Let me know if you need some early testing for that package... I currently have a setup where I have all separate streams for each participant recorded separately (1 video and 1 audio file for each participant).... starting to work on a system to track metadata about who active speaker is to go with the file set.

**Comment by Dirvann** [comment]
I'm not sure if ffmpeg is able to to wait for reconnection. I saw there is a setting for it on stack, but haven't tested.

Nice setup. Well if you want we can collab. 
What I have currently working is creating a single video file with as only input a list of video `paths` with their `start time`. And generates like a video conference type video file with people coming in and out. The layout is also customizable. 
The next steps would be:
- add support with video-only and audio-only files mixed in input list (currently only for video files containing audio)
- detect the active speaker to put in front of line, or define the main speaker

So the tracking of metadata would be useful for that. My idea was to get the audio into an array and calculate the places where there is a high variation.

**Comment by eabovsky** [comment]
Right - so my current goal is to implement video conferencing recording.

Layout is probably not as important for my use case, but there are a lot of
edge cases that must be considered:

   - For audio, the intent is to just mix all the audio streams together
   into one track.
   - If recording continuous streams, as active speaker changes, you might
   have several segments (time periods) from the same source video file to
   use. So, while I haven't started implementing yet, the first step in my
   pre-processing will likely be to extract the relevant clips for when a
   speaker is active.
   - Adding to the complexity is also that not everyone who is an active
   speaker will necessarily have their video on (some participants might be
   audio-only) - or turn off / on video during their active-speaking segment.
   Some kind of a filler image / avatar has to be put in place for cases when
   there is no corresponding video segment available.


I'm gonna hammer on ffmpeg a bit and see if there's a way to get it to
reconnect a different producer... that would be really ideal as it would
save a lot of that painful post-processing / filling / audio and video sync
issues / etc.

**Comment by Dirvann** [comment]
If you're up for it let's connect I can save a lot of your time with the ffmpeg. 

I've sent you an email with more details.

**Comment by dinceremre** [comment]
Guys , can you please provide info or samples of the outcomes?
I am also working on a similar scenario at which i am trying to put together a single video by combining several recordings.The goal is to publish that video back to  the audience.thanks in advance

**Comment by ethand91** [comment]
This is way out of the scope of this sample, might be a nightmare to implement and test but if you do it I would love for you to share how you implemented it. :)

**Comment by unkindypie** [comment]
I'm working on the same task right now. Have you guys come to any solution?

**Comment by ClubwealthTechteam** [comment]
I'm also trying to figure out how to do this, but am a complete novice to ffmpeg and gstreamer. I'll post in here if I make any progress though.

**Comment by tspecht** [comment]
> I'm currently working on a package that is able to combine all the separately recorded videos into one single video looking just like a web conference. I'll be releasing a first version soon.

@Dirvann do you have a progress update on that? :)

**Comment by Dirvann** [comment]
@tspecht @ClubwealthTechteam @universeroc @dinceremre @eabovsky @ethand91 
I published a first version of the package here:

https://github.com/Dirvann/video-conference-stitcher
https://www.npmjs.com/package/video-conference-stitcher

Feel free to do some pull requests and open issues for improvement.

Best regards

**Comment by ethand91** [comment]
Nice :)
I'll play around with it when I have time.
Closing this for now, as it's out of scope and the issue should be resolved by utilizing something like the above library.
