### ISSUE TITLE
Router and multiple workers

### ISSUE THREAD

**Issue by sstativa** [ethand91/mediasoup3-record-demo#29]
I've noticed a strange logic in the code.

You initialize multiple workers in `mediasoup.js` and have a function to get a next worker in "round-robin" style. However, it looks like on the start of `server.js` you create one router from the 1st available worker and never try to utilise other workers.

Am I missing something or this is really a bug? Should not you have one router per session?

**Comment by Dirvann** [comment]
You can actually use just one router for multiple sessions. That's no issue. 
The function does allow to distribute newly created routers over workers. It comes from the mediasoup-demo and is useful for expansion to multiple rooms for example.
In this case it isn't used that way as only one router is created. Just creating one router with a single worker would do the same thing.

**Comment by ethand91** [comment]
Creating multiple workers is so it can be expanded easier. 
However you are correct you may only need one worker, feel free to change the code to suit your requirements.
