### ISSUE TITLE
record for vp9 svc

### ISSUE THREAD

**Issue by aoslee** [ethand91/mediasoup3-record-demo#3]
Hi:
I tested the recording of VP9 SVC with ffmpeg and GStreamer respectively, and found that ffmpeg can not achieve this operation. GStreamer can record VP9 SVC, but only spatial_layer = 0. 
Refer to https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/blob/master/gst/rtp/gstrtpvp9depay.h.
My question is that there are any plans for recording in VP9 SVC, or how to set a spatial player to record?
Best regards

**Comment by ethand91** [comment]
Hello,
Thanks for the info regarding GStreamer and VP9 SVC.

I will try to support other codecs, when I get free time, however for "advanced" cases such as VP9 SVC support you may need to implement it yourself.
