### ISSUE TITLE
stop video button is disabled

### ISSUE THREAD

**Issue by samames** [ethand91/mediasoup3-record-demo#39]
stop video button is disabled after start button is clicked. Did I do something wrong, or is this a bug?

**Comment by ethand91** [comment]
Did recording actually start on the server side? If so does the file have any data?

**Comment by ethand91** [comment]
If recording doesn't start I don't think the button will be enabled.
In regards to the recording doesn't start that's a different issue, if you can open another issue and give logs I would be grateful.
