### ISSUE TITLE
Could not write header for output file

### ISSUE THREAD

**Issue by tazmanyak** [ethand91/mediasoup3-record-demo#42]
Hello,

I'm getting the error below. I run server and and app correctly but when i click record button, it gets this error and save record file as 0 byte.

![image](https://user-images.githubusercontent.com/1527013/110258186-51e80b00-7fb2-11eb-81f3-904680850120.png)

If you can help me about this problem, I will be very happy :))

Thanks in advance,

**Comment by ethand91** [comment]
It looks like the codecs are wrong?
For example ffmpeg expects VP8 but you are sending H264.

Please check your configurations/webrtc-internals to make sure they are both the same video/audio codec.
