### ISSUE TITLE
Documentation should explain the IP meaning and changes needed in this configuration

### ISSUE THREAD

**Issue by nagkumar** [ethand91/mediasoup3-record-demo#47]
webRtcTransport: {
    listenIps: [ { ip: '0.0.0.0', announcedIp: undefined } ], // TODO: Change announcedIp to your external IP or domain name
    enableUdp: true,
    enableTcp: true,
    preferUdp: true,
    maxIncomingBitrate: 1500000
  },
  plainRtpTransport: {
    listenIp: { ip: '0.0.0.0', announcedIp: undefined }, // TODO: Change announcedIp to your external IP or domain name
    rtcpMux: true,
    comedia: false
  }

**Comment by nagkumar** [comment]
Can you pl. explain what ip value should be is 0.0.0.0 ok or do we need to change it to URL IP used to access the server..
Also, announcedIp should it be changed (todo does say so), if yes, if I am accessing the server with IP say 192.168.0.23 then should I change announcedIp: 192.168.0.23

**Comment by ethand91** [comment]
You should change the announcedIp to the global ip of the server.
