### ISSUE TITLE
webm file garbled

### ISSUE THREAD

**Issue by funkju** [ethand91/mediasoup3-record-demo#5]
![image](https://user-images.githubusercontent.com/1482389/75126729-78bdf280-5678-11ea-98af-7f2bb10c71f1.png)

All of my recordings end up progressively glitching until they look like this. Any ideas to the cause?

Running on Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64
GStreamer version: GStreamer Core Library version 1.10.4

**Comment by ethand91** [comment]
Hello,

>All of my recordings end up progressively glitching until they look like this. Any ideas to the cause?

This may be caused by a large amount of packet loss.
Could you call "getStats" on the producer and consumer at an interval and check the packet loss?

**Comment by funkju** [comment]
What is a tolerable level of packet loss?

I have a 4 minute recording with the following stats:

`CONSUMER STATS:  [
  {
    bitrate: 36771,
    byteCount: 1244972,
    firCount: 0,
    fractionLost: 1,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 12347,
    packetsDiscarded: 0,
    packetsLost: 103,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 1.007080078125,
    score: 9,
    ssrc: 690202909,
    timestamp: 88748493,
    type: 'outbound-rtp'
  },
  {
    bitrate: 38371,
    byteCount: 1404218,
    firCount: 0,
    fractionLost: 1,
    jitter: 0,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 13407,
    packetsDiscarded: 0,
    packetsLost: 104,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 57.4951171875,
    score: 9,
    ssrc: 3065440649,
    timestamp: 88748493,
    type: 'inbound-rtp'
  }
]`

`PRODUCER STATS:  [
  {
    bitrate: 1756310,
    byteCount: 57136825,
    firCount: 0,
    fractionLost: 0,
    jitter: 0,
    kind: 'video',
    mimeType: 'video/VP8',
    nackCount: 147,
    nackPacketCount: 1058,
    packetCount: 49649,
    packetsDiscarded: 0,
    packetsLost: 343,
    packetsRepaired: 343,
    packetsRetransmitted: 532,
    pliCount: 1,
    roundTripTime: 57.952880859375,
    rtxSsrc: 407097086,
    score: 10,
    ssrc: 556314332,
    timestamp: 88748181,
    type: 'inbound-rtp'
  },
  {
    bitrate: 37987,
    byteCount: 1402619,
    firCount: 0,
    fractionLost: 1,
    jitter: 0,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 13393,
    packetsDiscarded: 0,
    packetsLost: 104,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 57.4951171875,
    score: 9,
    ssrc: 3065440649,
    timestamp: 88748214,
    type: 'inbound-rtp'
  }
]`


Packet loss seems pretty low. Here is the last frame of the video:

![image](https://user-images.githubusercontent.com/1482389/75254967-6c33ba00-579e-11ea-96ca-7f485488f768.png)

First "artifacts" start about 9 seconds in.

**Comment by funkju** [comment]
What is a tolerable level of packet loss?

I have a 4 minute recording with the following stats:

```
PRODUCER STATS:  [
  {
    bitrate: 1756310,
    byteCount: 57136825,
    firCount: 0,
    fractionLost: 0,
    jitter: 0,
    kind: 'video',
    mimeType: 'video/VP8',
    nackCount: 147,
    nackPacketCount: 1058,
    packetCount: 49649,
    packetsDiscarded: 0,
    packetsLost: 343,
    packetsRepaired: 343,
    packetsRetransmitted: 532,
    pliCount: 1,
    roundTripTime: 57.952880859375,
    rtxSsrc: 407097086,
    score: 10,
    ssrc: 556314332,
    timestamp: 88748181,
    type: 'inbound-rtp'
  }
]
PRODUCER STATS:  [
  {
    bitrate: 37987,
    byteCount: 1402619,
    firCount: 0,
    fractionLost: 1,
    jitter: 0,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 13393,
    packetsDiscarded: 0,
    packetsLost: 104,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 57.4951171875,
    score: 9,
    ssrc: 3065440649,
    timestamp: 88748214,
    type: 'inbound-rtp'
  }
]
CONSUMER STATS:  [
  {
    bitrate: 1734198,
    byteCount: 53826632,
    firCount: 0,
    fractionLost: 0,
    kind: 'video',
    mimeType: 'video/VP8',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 46736,
    packetsDiscarded: 0,
    packetsLost: 0,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    score: 9,
    ssrc: 507485967,
    timestamp: 88748492,
    type: 'outbound-rtp'
  },
  {
    bitrate: 1734198,
    byteCount: 57203999,
    firCount: 0,
    fractionLost: 0,
    jitter: 0,
    kind: 'video',
    mimeType: 'video/VP8',
    nackCount: 147,
    nackPacketCount: 1058,
    packetCount: 49708,
    packetsDiscarded: 0,
    packetsLost: 343,
    packetsRepaired: 343,
    packetsRetransmitted: 532,
    pliCount: 1,
    roundTripTime: 58.502197265625,
    rtxSsrc: 407097086,
    score: 10,
    ssrc: 556314332,
    timestamp: 88748492,
    type: 'inbound-rtp'
  }
]
CONSUMER STATS:  [
  {
    bitrate: 36771,
    byteCount: 1244972,
    firCount: 0,
    fractionLost: 1,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 12347,
    packetsDiscarded: 0,
    packetsLost: 103,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 1.007080078125,
    score: 9,
    ssrc: 690202909,
    timestamp: 88748493,
    type: 'outbound-rtp'
  },
  {
    bitrate: 38371,
    byteCount: 1404218,
    firCount: 0,
    fractionLost: 1,
    jitter: 0,
    kind: 'audio',
    mimeType: 'audio/opus',
    nackCount: 0,
    nackPacketCount: 0,
    packetCount: 13407,
    packetsDiscarded: 0,
    packetsLost: 104,
    packetsRepaired: 0,
    packetsRetransmitted: 0,
    pliCount: 0,
    roundTripTime: 57.4951171875,
    score: 9,
    ssrc: 3065440649,
    timestamp: 88748493,
    type: 'inbound-rtp'
  }
]
```
Packet loss seems pretty low. 

First "artifacts" start about 9 seconds in.

**Comment by ethand91** [comment]
Your right, packet loss is not too bad..

Could you try the following:
update GStreamer to version 1.16.0 (which is the version I used making this)
also does gstreamer print any WARN logs to the console? You could try setting GSTREAMER_DEBUG_LEVEL to 4/5 to get more info.

**Comment by ethand91** [comment]
Thanks I'll look into it.

**Comment by ethand91** [comment]
Hello would it be possible for you to provide the webm file?

**Comment by funkju** [comment]
Here is a link to it: https://we.tl/t-NrMdLQWZpx

Github wont accept the file because it's too large. If you don't trust the random websharing link - I can record a smaller one to provide.

**Comment by ethand91** [comment]
Hello could you please create and share a smaller one

**Comment by ethand91** [comment]
closed due to inactivity
