### ISSUE TITLE
FFMPEG process with piped streams

### ISSUE THREAD

**Issue by beingmountain23** [ethand91/mediasoup3-record-demo#6]
Hi Ethan,
I have attempted to consume piped streams and create a new webm file similar to your implementation.

I pipe audio and video streams, to a different server, and create two consumer objects. This step works successfully.

But when I begin an ffmpeg process with these consumers, it always enters stderr hook of the process and prints the ffmpeg banner.
It doesn't seem to start recording.

Did you face something like this? Can you tell me if I'm doing something wrong?

**Comment by ethand91** [comment]
Hello,

if the ffmpeg process exits immediantly it's usually due to a bad pipeline.
Could you share the ffmpeg command you are using?

**Comment by beingmountain23** [comment]
Hi,
When the ffmpeg process fails immediately, I had been using the same command as you used in your process. 


I also tried using the following command:
ffmpeg -loglevel debug -protocol_whitelist file, crypto, udp, rtp -analyzeduration 2147483647 -probesize 2147483647 -i sdpfile -vcodec copy -acodec copy -y output.webm

But this one gives me a stream error:
'Could not find codec parameters for stream 0'

**Comment by ethand91** [comment]
>When the ffmpeg process fails immediately, I had been using the same command as you used in your process.

Could you tell me what the error is when trying to use my command?

Also could you tell me the version of FFmpeg you are using?
Another possibility is that the consumer isn't actually sending anything so could you check the stats of the consumer (via getStats()) and see if packets are actually being sent?

**Comment by beingmountain23** [comment]
Hi Ethan,
Upon inspection I realized that I'm actually using the enable srtp configuration of the latest mediasoup.
That's why it's malfunctioning.

Could that be the problem? I'll try it out and check how to enable srtp on ffmpeg.



Also, the consumers are showing incoming traffic correctly, no issues there.

**Comment by ethand91** [comment]
>I'll try it out and check how to enable srtp on ffmpeg.

Please try and let me know if it works

**Comment by beingmountain23** [comment]
Do you know if I need to modify the SDP file for srtp streams? 
I understood how to modify the ffmpeg command...
But I don't know about the SDP file contents.

**Comment by ethand91** [comment]
Don't think you need to modify the SDP file for srtp streams.
Could you share the contents of the sdp file?

**Comment by beingmountain23** [comment]
Hi Ethan,
When ever I spawn a process, it enters stderr. These are the arguments I am passing to the process:
  get _commandArgs() {
        let commandArgs = [
            '-analyzeduration',
            '2147483647',
            '-probesize',
            '2147483647',
            '-hide_banner',
            '-loglevel',
            'debug',
            '-protocol_whitelist',
            'pipe,udp,rtp',
            '-fflags',
            '+genpts',
            '-f',
            'sdp',
            '-i',
            'pipe:0'
        ];

 
        commandArgs = commandArgs.concat(this._videoArgs);
        commandArgs = commandArgs.concat(this._audioArgs);

        commandArgs = commandArgs.concat([
            '-flags',
            '+global_header',
            `${RECORD_FILE_LOCATION_PATH}/${this._fileName}/%05d.webm`
        ]);

        console.log('commandArgs:%o', commandArgs);

        return commandArgs;
    }

    get _videoArgs() {
        return [
            '-map',
            '0:v:0',
            '-c:v',
            'copy'
        ];
    }

    get _audioArgs() {
        return [
            '-map',
            '0:a:0',
            '-strict',
            '-2',
            '-c:v',
            'copy'
        ];
    }
The logs are shown below:
![ffmpeg_error_crop](https://user-images.githubusercontent.com/31466986/78246403-b713c080-7506-11ea-87b5-d0e58f10e923.png)


Please tell me what I am doing wrong?

**Comment by ethand91** [comment]
If you haven't already, could you try changing src/config.js plainRtpTransport.listenIp to the server's network/global IP.

Also could you show the full log of the above screenshot

**Comment by beingmountain23** [comment]
Hi Ethan,
Sorry for the delay. I had to restructure some part of my code, but now I have encountered the below problem in FFMPEG:
![Screenshot from 2020-04-07 08-10-39](https://user-images.githubusercontent.com/31466986/78646102-162b5980-78a8-11ea-9446-29e15195ef9c.png)

This is what my sdp looks like:
`      v=0
        o=- 0 0 IN IP4 127.0.0.1
        s=FFmpeg
        c=IN IP4 127.0.0.1
        t=0 0
        m=video ${this.recordingVideoConsumer.remoteRtpPort} RTP/AVP 101
        a=rtpmap:101 VP8/90000
        a=sendonly
        m=audio ${this.recordingAudioConsumer.remoteRtpPort} RTP/AVP 100
        a=rtpmap:100 opus/48000/2
        a=sendonly`;

**Comment by beingmountain23** [comment]
What I understand from reading up about the error is that, I am not actually sending in VP8 even though it is specified in my SDP file. If that's the case then should I set my video parameter dynamically in the SDP file? based on the media codecs that my consumer is receiving?

**Comment by ethand91** [comment]
Hello, could you share the full rtpParameters of "recordingVideoConsumer"?

**Comment by beingmountain23** [comment]
Hi Ethan,
Here are the values for audio and video RTP parameters:
![RTP Params](https://user-images.githubusercontent.com/31466986/78666646-2a328380-78c7-11ea-823c-ebc955a13b56.png)

I see the values are VP8 and OPUS so it should be consuming correctly.

**Comment by ethand91** [comment]
Hello, the error is saying "No such file or directory",
could you make sure your directory path is correct?

**Comment by beingmountain23** [comment]
Hi Ethan,
I corrected the file path.
I also understood what was wrong.

The consumers were not resumed correctly. I checked the consumer stats and realized the problem.

Thank you for all your help.

**Comment by ethand91** [comment]
Great to hear you got it sorted.

**Comment by abhinavsy** [comment]
Hi ethan,
I got this when i stop the record button.And also the video file was  0 bytes.Whats wrong in here?
![Screenshot from 2022-08-11 10-20-02](https://user-images.githubusercontent.com/104485114/184066802-2eba1cca-1a9e-4a63-a74d-59eb12a149a4.png)

**Comment by apoduval23** [comment]
Looks like the specified codec is wrong, Can you share the options you're passing to ffmpeg?
