### ISSUE TITLE
Firefox not recording

### ISSUE THREAD

**Issue by hadiaec20h** [ethand91/mediasoup3-record-demo#63]
I tried to record with Firefox, but it failed recording and recording file is 0 bytes. However recording with chrome is OK.

This is the latest message of ffmpeg:

```
ffmpeg::process::data [data:'[mp4 @ 0x55ef198365c0] dimensions not set\n' +
  'Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument\n' +
  'Error initializing output stream 0:1 -- \n' +
  'Stream mapping:\n' +
  '  Stream #0:0 -> #0:0 (copy)\n' +
  '  Stream #0:1 -> #0:1 (copy)\n' +
  '    Last message repeated 1 times\n' +
  '[AVIOContext @ 0x55ef19839bc0] Statistics: 0 seeks, 0 writeouts\n' +
  '[AVIOContext @ 0x55ef197c0380] Statistics: 210 bytes read, 0 seeks\n']
ffmpeg::process::close```
```

`ffmpeg-static": "^4.4.0"`
`mediasoup": "^3.8.4"`
`ffmpeg --version : 4.4
`

any ideas?

**Comment by ethand91** [comment]
"ffmpeg-static", the sample does not use this package. Will see if I can reproduce here.

**Comment by ethand91** [comment]
Updated, open again if you experience the same issue.
