### ISSUE TITLE
ffmpeg record error 

### ISSUE THREAD

**Issue by myseawp** [ethand91/mediasoup3-record-demo#7]
hi ,i met the error：

<pre>ffmpeg::process::data [data:'[sdp @ 0x6b903c0] Could not find codec parameters for stream 0 (Video: vp8, 1 reference frame, yuv420p): unspecified size\n' +
  "Consider increasing the value for the 'analyzeduration' and 'probesize' options\n" +
  '[sdp @ 0x6b903c0] After avformat_find_stream_info() pos: 208 bytes read:208 seeks:0 frames:0\n']
ffmpeg::process::data [data:"Input #0, sdp, from 'pipe:0':\n" +
  '  Metadata:\n' +
  '    title           : FFmpeg\n' +
  '  Duration: N/A, bitrate: N/A\n' +
  '    Stream #0:0, 0, 1/90000: Video: vp8, 1 reference frame, yuv420p, 90k tbr, 90k tbn, 90k tbc\n' +
  '    Stream #0:1, 0, 1/48000: Audio: opus, 48000 Hz, stereo, fltp\n' +
  'Successfully opened the file.\n' +
  'Parsing a group of options: output url /root/recording/files/1585644824875.webm.\n' +
  'Applying option map (set input stream mapping) with argument 0:v:0.\n' +
  'Applying option c:v (codec name) with argument copy.\n' +
  'Applying option map (set input stream mapping) with argument 0:a:0.\n' +
  'Applying option c:a (codec name) with argument copy.\n' +
  'Successfully parsed a group of options.\n' +
  'Opening an output file: /root/recording/files/1585644824875.webm.\n' +
  "[file @ 0x6bebf40] Setting default whitelist 'file,crypto'\n" +
  'Successfully opened the file.\n']
ffmpeg::process::data [data:'[webm @ 0x6ba0700] dimensions not set\n' +
  'Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument\n' +
  'Stream mapping:\n' +
  '  Stream #0:0 -> #0:0 (copy)\n' +
  '  Stream #0:1 -> #0:1 (copy)\n' +
  '    Last message repeated 1 times\n' +
  '[AVIOContext @ 0x6b9ca80] Statistics: 0 seeks, 0 writeouts\n' +
  '[AVIOContext @ 0x6b99300] Statistics: 208 bytes read, 0 seeks\n']</pre>

i also see the same error in ：https://github.com/ethand91/mediasoup3-record-demo/issues/4

i follow the suggestion，but the error is all the same .
OS: ubuntu 18.04
& 
FFMPEG: install ffmpeg form source:https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

when test with ffmpeg: 
`ffmpeg -codecs | grep vp8`

the result is:
<pre>ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
 DEV.L. vp8                  On2 VP8 (decoders: vp8 vp8_v4l2m2m libvpx ) (encoders: libvpx vp8_v4l2m2m )
</pre>

Can you help me?Thanks.

**Comment by ethand91** [comment]
Hello,

Could you tried adding "-analyzeduration 2147483647 -probesize 2147483647" to the beginning of the ffmpeg command args.

**Comment by myseawp** [comment]
hi
I add the -analyzeduration and -probesize option into the ffmpeg.js
<pre>
  get _commandArgs () {
    let commandArgs = [
      '-analyzeduration',
      '2147483647',
      '-probesize',
      '2147483647',
      '-loglevel',
      'debug',
      '-protocol_whitelist',
      'pipe,udp,rtp',
      '-fflags',
      '+genpts',
      '-f',
      'sdp',
      '-i',
      'pipe:0'
    ];
</pre>

and the error is also:

<pre>
ffmpeg::process::data [data:'ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers\n' +
  '  built with gcc 8 (Debian 8.3.0-6)\n' +
  '  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg\n' +
  '  libavutil      56. 31.100 / 56. 31.100\n' +
  '  libavcodec     58. 54.100 / 58. 54.100\n' +
  '  libavformat    58. 29.100 / 58. 29.100\n' +
  '  libavdevice    58.  8.100 / 58.  8.100\n' +
  '  libavfilter     7. 57.100 /  7. 57.100\n' +
  '  libswscale      5.  5.100 /  5.  5.100\n' +
  '  libswresample   3.  5.100 /  3.  5.100\n' +
  '  libpostproc    55.  5.100 / 55.  5.100\n' +
  'Splitting the commandline.\n' +
  "Reading option '-analyzeduration' ..."]
ffmpeg::process::data [data:" matched as AVOption 'analyzeduration' with argument '2147483647'.\n" +
  "Reading option '-probesize' ..."]
ffmpeg::process::data [data:" matched as AVOption 'probesize' with argument '2147483647'.\n" +
  "Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.\n" +
  "Reading option '-protocol_whitelist' ..."]
ffmpeg::process::data [data:" matched as AVOption 'protocol_whitelist' with argument 'pipe,udp,rtp'.\n" +
  "Reading option '-fflags' ..."]
ffmpeg::process::data [data:" matched as AVOption 'fflags' with argument '+genpts'.\n" +
  "Reading option '-f' ... matched as option 'f' (force format) with argument 'sdp'.\n" +
  "Reading option '-i' ... matched as input url with argument 'pipe:0'.\n" +
  "Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:v:0'.\n" +
  "Reading option '-c:v' ... matched as option 'c' (codec name) with argument 'copy'.\n" +
  "Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '0:a:0'.\n" +
  "Reading option '-strict' ..."]
ffmpeg::process::data [data:'Routing option strict to both codec and muxer layer\n' +
  " matched as AVOption 'strict' with argument '-2'.\n" +
  "Reading option '-c:a' ... matched as option 'c' (codec name) with argument 'copy'.\n" +
  "Reading option '-flags' ..."]
ffmpeg::process::data [data:" matched as AVOption 'flags' with argument '+global_header'.\n" +
  "Reading option '/root/recording/files/1585703359744.webm' ... matched as output url.\n" +
  'Finished splitting the commandline.\n' +
  'Parsing a group of options: global .\n' +
  'Applying option loglevel (set logging level) with argument debug.\n' +
  'Successfully parsed a group of options.\n' +
  'Parsing a group of options: input url pipe:0.\n' +
  'Applying option f (force format) with argument sdp.\n' +
  'Successfully parsed a group of options.\n' +
  'Opening an input file: pipe:0.\n' +
  "[sdp @ 0x6f20400] Opening 'pipe:0' for reading\n"]
ffmpeg::process::data [data:'[sdp @ 0x6f20400] video codec set to: vp8\n']
ffmpeg::process::data [data:'[sdp @ 0x6f20400] audio codec set to: opus\n' +
  '[sdp @ 0x6f20400] audio samplerate set to: 48000\n' +
  '[sdp @ 0x6f20400] audio channels set to: 2\n' +
  '[udp @ 0x6f28cc0] end receive buffer size reported is 131072\n']
ffmpeg::process::data [data:'[udp @ 0x6f287c0] end receive buffer size reported is 131072\n' +
  '[sdp @ 0x6f20400] setting jitter buffer size to 500\n' +
  '[udp @ 0x6f21dc0] end receive buffer size reported is 131072\n' +
  '[udp @ 0x6f217c0] end receive buffer size reported is 131072\n' +
  '[sdp @ 0x6f20400] setting jitter buffer size to 500\n' +
  '[sdp @ 0x6f20400] Before avformat_find_stream_info() pos: 208 bytes read:208 seeks:0 nb_streams:2\n']
ffmpeg::process::data [data:'[sdp @ 0x6f20400] Could not find codec parameters for stream 0 (Video: vp8, 1 reference frame, yuv420p): unspecified size\n' +
  "Consider increasing the value for the 'analyzeduration' and 'probesize' options\n"]
ffmpeg::process::data [data:'[sdp @ 0x6f20400] After avformat_find_stream_info() pos: 208 bytes read:208 seeks:0 frames:0\n' +
  "Input #0, sdp, from 'pipe:0':\n"]
ffmpeg::process::data [data:'  Metadata:\n' +
  '    title           : FFmpeg\n' +
  '  Duration: N/A, bitrate: N/A\n' +
  '    Stream #0:0, 0, 1/90000: Video: vp8, 1 reference frame, yuv420p, 90k tbr, 90k tbn, 90k tbc\n' +
  '    Stream #0:1, 0, 1/48000: Audio: opus, 48000 Hz, stereo, fltp\n' +
  'Successfully opened the file.\n' +
  'Parsing a group of options: output url /root/recording/files/1585703359744.webm.\n' +
  'Applying option map (set input stream mapping) with argument 0:v:0.\n']
ffmpeg::process::data [data:'Applying option c:v (codec name) with argument copy.\n' +
  'Applying option map (set input stream mapping) with argument 0:a:0.\n' +
  'Applying option c:a (codec name) with argument copy.\n' +
  'Successfully parsed a group of options.\n' +
  'Opening an output file: /root/recording/files/1585703359744.webm.\n']
ffmpeg::process::data [data:"[file @ 0x6f7c940] Setting default whitelist 'file,crypto'\n"]
ffmpeg::process::data [data:'Successfully opened the file.\n' +
  '[webm @ 0x6f30a40] dimensions not set\n' +
  'Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument\n' +
  'Stream mapping:\n' +
  '  Stream #0:0 -> #0:0 (copy)\n' +
  '  Stream #0:1 -> #0:1 (copy)\n' +
  '    Last message repeated 1 times\n' +
  '[AVIOContext @ 0x6f7c7c0] Statistics: 0 seeks, 0 writeouts\n' +
  '[AVIOContext @ 0x6f296c0] Statistics: 208 bytes read, 0 seeks\n']
ffmpeg::process::close/pre>

**Comment by ethand91** [comment]
It looks like it's not reading the vp8 track correctly, have you changed the mediasoup config file?
Also could you check the mediasoup debug logs?

**Comment by myseawp** [comment]
hi,I found the error.
the error is  i change the webRtcTransport ip to "0.0.0.0",
when update it to the local ip , that is ok!

Thanks!

**Comment by ethand91** [comment]
Great! Thanks for sharing your solution :)
