### ISSUE TITLE
Multiple bitrate hls output

### ISSUE THREAD

**Issue by lelikg** [ethand91/mediasoup3-record-demo#8]
Hi, how would I go about outputting multi-bitrate hls from the incoming rtp stream with gstreamer?

**Comment by ethand91** [comment]
Hello,

You could get the stream from mediasoup using gstreamer's rtpbin/udpsink, and then create the hls files using hlssink.
Another way is to convert RTP to RTMP using gstreamer and using another media server to convert the RTMP stream to HLS.
Though this is outside the scope of this project.

**Comment by lelikg** [comment]
Thanks for answering!
I would be happy to consult with you on the gstreamer command for teeing one input into three different resolution renditions, I tried the hlssink myself but ran into several issues.
